export const TOPICS = [
    // Tier 1 – Novice
    { id: 1, text: 'Luck', tier: 1 },
    { id: 2, text: 'Morning Routines', tier: 1 },
    { id: 3, text: 'Inside Voice', tier: 1 },
    { id: 4, text: 'Fear', tier: 1 },
    { id: 5, text: 'First Impressions', tier: 1 },
    { id: 6, text: 'Comfort Zone', tier: 1 },
    { id: 7, text: 'Silence', tier: 1 },
    { id: 8, text: 'Eye Contact', tier: 1 },
    { id: 9, text: 'Body Language', tier: 1 },
    { id: 10, text: 'Mistakes', tier: 1 },
    { id: 11, text: 'Gratitude', tier: 1 },
    { id: 12, text: 'Change', tier: 1 },
    { id: 13, text: 'Time', tier: 1 },
    { id: 14, text: 'Confidence', tier: 1 },
    { id: 15, text: 'Listening', tier: 1 },
    { id: 16, text: 'Failure', tier: 1 },
    { id: 17, text: 'Focus', tier: 1 },
    { id: 18, text: 'Boredom', tier: 1 },
    { id: 19, text: 'Kindness', tier: 1 },
    { id: 20, text: 'Trust', tier: 1 },
    // Tier 2 – Confident
    { id: 21, text: 'Analysis Paralysis', tier: 2 },
    { id: 22, text: 'Social Media', tier: 2 },
    { id: 23, text: 'Vulnerability', tier: 2 },
    { id: 24, text: 'Discipline', tier: 2 },
    { id: 25, text: 'Envy', tier: 2 },
    { id: 26, text: 'Imposter Syndrome', tier: 2 },
    { id: 27, text: 'Growth Mindset', tier: 2 },
    { id: 28, text: 'Empathy', tier: 2 },
    { id: 29, text: 'Overthinking', tier: 2 },
    { id: 30, text: 'Peer Pressure', tier: 2 },
    { id: 31, text: 'Identity', tier: 2 },
    { id: 32, text: 'Success', tier: 2 },
    { id: 33, text: 'Procrastination', tier: 2 },
    { id: 34, text: 'Ego', tier: 2 },
    { id: 35, text: 'Competition', tier: 2 },
    { id: 36, text: 'Sacrifice', tier: 2 },
    { id: 37, text: 'Addiction', tier: 2 },
    { id: 38, text: 'Belonging', tier: 2 },
    { id: 39, text: 'Risk', tier: 2 },
    { id: 40, text: 'Rejection', tier: 2 },
    // Tier 3 – Orator
    { id: 41, text: 'Moral Courage', tier: 3 },
    { id: 42, text: 'Echo Chambers', tier: 3 },
    { id: 43, text: 'Authenticity', tier: 3 },
    { id: 44, text: 'Luck vs. Skill', tier: 3 },
    { id: 45, text: 'Power of Habit', tier: 3 },
    { id: 46, text: 'Privilege', tier: 3 },
    { id: 47, text: 'Meritocracy', tier: 3 },
    { id: 48, text: 'Status', tier: 3 },
    { id: 49, text: 'Empathy Gap', tier: 3 },
    { id: 50, text: 'Tribe Mentality', tier: 3 },
    { id: 51, text: 'Legacy', tier: 3 },
    { id: 52, text: 'Purpose', tier: 3 },
    { id: 53, text: 'Silence as Power', tier: 3 },
    { id: 54, text: 'Narrative Bias', tier: 3 },
    { id: 55, text: 'Illusion of Control', tier: 3 },
    { id: 56, text: 'Scarcity Mindset', tier: 3 },
    { id: 57, text: 'Death', tier: 3 },
    { id: 58, text: 'Humility', tier: 3 },
    { id: 59, text: 'Redemption', tier: 3 },
    { id: 60, text: 'Forgiveness', tier: 3 },
    // Tier 4 – Keynote
    { id: 61, text: 'Systems vs. Goals', tier: 4 },
    { id: 62, text: 'Cognitive Dissonance', tier: 4 },
    { id: 63, text: 'Collective Trauma', tier: 4 },
    { id: 64, text: 'Power Dynamics', tier: 4 },
    { id: 65, text: 'Truth', tier: 4 },
    { id: 66, text: 'The Unknown', tier: 4 },
    { id: 67, text: 'Free Will', tier: 4 },
    { id: 68, text: 'Groupthink', tier: 4 },
    { id: 69, text: 'Sunk Cost Fallacy', tier: 4 },
    { id: 70, text: 'Moral Relativism', tier: 4 },
    { id: 71, text: 'The Long Game', tier: 4 },
    { id: 72, text: 'Uncertainty', tier: 4 },
    { id: 73, text: 'Sacrifice vs. Compromise', tier: 4 },
    { id: 74, text: 'Information Overload', tier: 4 },
    { id: 75, text: 'Responsibility', tier: 4 },
    { id: 76, text: 'Forgetting', tier: 4 },
    { id: 77, text: 'Adaptation', tier: 4 },
    { id: 78, text: 'Courage', tier: 4 },
    { id: 79, text: 'The Narrative Self', tier: 4 },
    { id: 80, text: 'Presence', tier: 4 },
    // Tier 5 – Legend
    { id: 81, text: 'The Paradox of Choice', tier: 5 },
    { id: 82, text: 'Infinite Games', tier: 5 },
    { id: 83, text: 'Meaning', tier: 5 },
    { id: 84, text: 'Transcendence', tier: 5 },
    { id: 85, text: 'The Observer Effect', tier: 5 },
    { id: 86, text: 'First Principles', tier: 5 },
    { id: 87, text: 'Emergent Behavior', tier: 5 },
    { id: 88, text: 'The Banality of Evil', tier: 5 },
    { id: 89, text: 'Signal vs. Noise', tier: 5 },
    { id: 90, text: 'Radical Honesty', tier: 5 },
    { id: 91, text: 'Memento Mori', tier: 5 },
    { id: 92, text: 'Amor Fati', tier: 5 },
    { id: 93, text: 'The Hedonic Treadmill', tier: 5 },
    { id: 94, text: 'Existential Risk', tier: 5 },
    { id: 95, text: 'The Pale Blue Dot', tier: 5 },
    { id: 96, text: 'Long-term Thinking', tier: 5 },
    { id: 97, text: 'The Void', tier: 5 },
    { id: 98, text: 'Interconnectedness', tier: 5 },
    { id: 99, text: 'The Present Moment', tier: 5 },
    { id: 100, text: 'What Is Enough', tier: 5 },
];

export const TIPS = [
    { id: 1, text: "Show up to give, not to take. Don't approach your speech seeking approval or validation — show up to provide pure value. Audiences sense immediately whether you're a giver or a taker.", speaker: "Simon Sinek", tier: 1 },
    { id: 2, text: "Don't talk right away. Walk out, take a breath, and pause for a few seconds before your first word. Silence at the start signals confidence and commands attention.", speaker: "Simon Sinek", tier: 1 },
    { id: 3, text: "Make eye contact one person at a time. Give each person one full sentence with direct eye contact. This transforms a lecture into a conversation.", speaker: "Simon Sinek", tier: 1 },
    { id: 4, text: "Speak unusually slowly. Audiences are far more patient than speakers think. Slowing down shows control and makes every word land harder.", speaker: "Simon Sinek", tier: 2 },
    { id: 5, text: "Be as big as the room. Adjust your energy, volume, and presence to match the size of your audience. A whisper fails in an auditorium; a shout overwhelms a boardroom.", speaker: "Vinh Giang", tier: 1 },
    { id: 6, text: "End on a lower pitch. Finishing a sentence with a downward inflection signals certainty and authority. An upward pitch sounds like a question — even when it isn't.", speaker: "Vinh Giang", tier: 2 },
    { id: 7, text: "Pause. Let them catch up. A pause is not dead air — it's a gift to your audience. It gives them time to process, and gives you time to think.", speaker: "Vinh Giang", tier: 1 },
    { id: 8, text: "You can still be shy. Just be louder. Volume isn't about personality — it's about vitality. Injecting volume shows life, even if you feel nervous inside.", speaker: "Vinh Giang", tier: 1 },
    { id: 9, text: "The meaning is beyond the words. How you use your voice — pace, pitch, tone, silence — carries as much meaning as what you actually say. Master both.", speaker: "Vinh Giang", tier: 2 },
    { id: 10, text: "Use movement with purpose. Every step you take on stage sends a signal. Move toward the audience when you want to connect; step back when you want them to reflect.", speaker: "Vinh Giang", tier: 2 },
    { id: 11, text: "Call out the elephant in the room. If there is obvious tension or discomfort — name it. Acknowledging it immediately releases it and earns trust.", speaker: "Vinh Giang", tier: 2 },
    { id: 12, text: "Tap your audience's emotions. Information without emotion is forgotten. To make your message stick, feel it yourself first — then your audience will feel it too.", speaker: "Tony Robbins", tier: 2 },
    { id: 13, text: "Add more value than anyone expects. Go deeper, give more, be more passionate than required. The speaker who overdelivers is the one people remember.", speaker: "Tony Robbins", tier: 3 },
    { id: 14, text: "Know your audience before you open your mouth. Research their fears, desires, and needs. A message that doesn't speak to the person in front of you is just noise.", speaker: "Tony Robbins", tier: 2 },
    { id: 15, text: "Where focus goes, energy flows. Before you speak, decide exactly what outcome you want for your audience — and anchor your entire talk to that single outcome.", speaker: "Tony Robbins", tier: 3 },
    { id: 16, text: "Don't speak about what you don't truly care about. Passion is not optional — it's the foundation of belief. If you don't believe it, they won't either.", speaker: "Tony Robbins", tier: 3 },
    { id: 17, text: "Every action you take is a vote for the type of speaker you wish to become. Every practice session, however small, is a deposit in your speaking identity.", speaker: "James Clear", tier: 1 },
    { id: 18, text: "You do not rise to the level of your goals. You fall to the level of your systems. Build a daily speaking practice — not just an ambition.", speaker: "James Clear", tier: 3 },
    { id: 19, text: "Be willing to look foolish while you learn. The fear of imperfection is the #1 enemy of improvement. The best speakers were once the worst in the room.", speaker: "James Clear", tier: 1 },
    { id: 20, text: "Start with Why. Before you explain what you do or how you do it, tell us why. People don't buy what you do — they buy why you do it.", speaker: "Simon Sinek", tier: 3 },
];

export function getRandomTopicForTier(tier: number, seenIds: number[]) {
    const available = TOPICS.filter(t => t.tier <= tier && !seenIds.includes(t.id));
    if (available.length === 0) return TOPICS.filter(t => t.tier <= tier)[0];
    return available[Math.floor(Math.random() * available.length)];
}

export function getRandomTipForTier(tier: number) {
    const pool = TIPS.filter(t => t.tier <= tier);
    return pool[Math.floor(Math.random() * pool.length)];
}
